# Site settings
title:          Jackie Chan
description:    "Code, Create, Reflect"
baseurl:        ""
url:            "https://jackiechanmakes.github.io"

# Google Analytics
google_analytics: G-8NFE7FB71S

# Author
author:
  name:         Jackie Chan
  url:          https://jackiechanmakes.github.io
  email:        jackiechanmakes@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jackiechanmakes-github-io